// Fallback workout data — used when the API is unreachable
// Matches the structure returned by https://api.abcz.workers.dev/api/fitlog

const fallbackWorkouts = [
  {
    id: 1,
    name: 'Pull-Up',
    description:
      'The pull-up is a foundational upper-body compound movement that builds serious back, bicep, and grip strength. Control every rep and focus on full range of motion.',
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
    muscleGroups: ['Back', 'Arms'],
    equipment: 'Pull-up Bar',
    difficulty: 'Intermediate',
    sets: 4,
    reps: '8-10',
    duration: 15,
    caloriesBurned: 120,
    rating: 4.7,
    instructions: [
      'Grip the bar slightly wider than shoulder-width, palms facing away.',
      'Hang with fully extended arms and engage your core.',
      'Pull your chest up toward the bar by driving your elbows down.',
      'Lower slowly back to the starting position with control.',
    ],
  },
  {
    id: 2,
    name: 'Barbell Bench Press',
    description:
      'A classic chest builder. The barbell bench press targets the pectorals, triceps, and front deltoids while building serious upper-body pushing strength.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
    muscleGroups: ['Chest'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    sets: 4,
    reps: '6-8',
    duration: 25,
    caloriesBurned: 180,
    rating: 4.8,
    instructions: [
      'Lie on the bench with eyes under the bar and feet planted.',
      'Unrack with locked elbows and lower the bar to mid-chest.',
      'Press up in a slight arc until elbows lock without bouncing.',
      'Keep shoulder blades pinched and a natural arch in the back.',
    ],
  },
  {
    id: 3,
    name: 'Back Squat',
    description:
      'The king of lower-body lifts. Back squats build raw strength and muscle across the quads, glutes, hamstrings, and core while improving mobility and posture.',
    image: 'https://images.unsplash.com/photo-1566241440091-ec10de8db2e1?w=800&q=80',
    muscleGroups: ['Legs'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    sets: 4,
    reps: '8-10',
    duration: 20,
    caloriesBurned: 150,
    rating: 4.6,
    instructions: [
      'Rest the bar across your upper back with a secure grip.',
      'Stand with feet shoulder-width apart, toes slightly out.',
      'Brace your core and lower by pushing your hips back and bending knees.',
      'Drive through your heels to stand back up to full height.',
    ],
  },
  {
    id: 4,
    name: 'Deadlift',
    description:
      'The deadlift is the ultimate total-body strength builder. It engages nearly every muscle group from head to toe and builds a posterior chain like nothing else.',
    image: 'https://images.unsplash.com/photo-1598575436823-e89f8eb9ce15?w=800&q=80',
    muscleGroups: ['Back', 'Legs'],
    equipment: 'Barbell',
    difficulty: 'Advanced',
    sets: 4,
    reps: '5-6',
    duration: 22,
    caloriesBurned: 200,
    rating: 4.9,
    instructions: [
      'Stand with feet hip-width, bar over mid-foot.',
      'Hinge at the hips and grip the bar just outside your knees.',
      'Brace your core, chest up, and drive through your heels.',
      'Stand tall with shoulders back, then lower with control.',
    ],
  },
  {
    id: 5,
    name: 'Dumbbell Bicep Curl',
    description:
      'Isolate your biceps with classic dumbbell curls. This staple arm exercise builds size and definition in the biceps while improving elbow and wrist stability.',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&q=80',
    muscleGroups: ['Arms'],
    equipment: 'Dumbbells',
    difficulty: 'Beginner',
    sets: 3,
    reps: '10-12',
    duration: 12,
    caloriesBurned: 80,
    rating: 4.3,
    instructions: [
      'Stand tall with dumbbells at your sides, palms forward.',
      'Curl the weights without swinging the torso.',
      'Squeeze at the top, then lower until arms are fully extended.',
      'Keep elbows pinned near the ribs throughout.',
    ],
  },
  {
    id: 6,
    name: 'Push-Up',
    description:
      'The ultimate bodyweight pushing exercise. Push-ups build chest, shoulder, and tricep strength while engaging the entire core for stability.',
    image: 'https://images.unsplash.com/photo-1598971639058-fab0d8077370?w=800&q=80',
    muscleGroups: ['Chest', 'Arms'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    sets: 3,
    reps: '12-15',
    duration: 10,
    caloriesBurned: 90,
    rating: 4.5,
    instructions: [
      'Start in a high plank position, hands slightly wider than shoulders.',
      'Lower your chest toward the floor while keeping your body straight.',
      'Push back up until your arms are fully extended.',
      'Keep your core braced and avoid sagging your hips.',
    ],
  },
  {
    id: 7,
    name: 'Russian Twist',
    description:
      'A rotational core exercise that targets the obliques and deep abdominal muscles. Great for building rotational strength and torso stability.',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80',
    muscleGroups: ['Core'],
    equipment: 'Medicine Ball',
    difficulty: 'Intermediate',
    sets: 3,
    reps: '20-25',
    duration: 8,
    caloriesBurned: 70,
    rating: 4.1,
    instructions: [
      'Sit on the floor with knees bent, holding a medicine ball at chest level.',
      'Lean back slightly and lift your feet off the floor for balance.',
      'Twist your torso to the right, then to the left — that is one rep.',
      'Keep your core tight and move with control the whole time.',
    ],
  },
  {
    id: 8,
    name: 'Hollow-Body Plank',
    description:
      'An advanced plank variation that cranks up core tension. The hollow-body position targets the entire anterior core and improves full-body stability.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
    muscleGroups: ['Core'],
    equipment: 'Bodyweight',
    difficulty: 'Intermediate',
    sets: 3,
    reps: '30-45s',
    duration: 10,
    caloriesBurned: 60,
    rating: 4.4,
    instructions: [
      'Set elbows under shoulders and squeeze glutes and quads.',
      'Tuck the pelvis so the lower back stays flat.',
      'Breathe into the brace without sagging the hips.',
      'Hold for the prescribed time, then rest and repeat.',
    ],
  },
  {
    id: 9,
    name: 'Lunge',
    description:
      'A unilateral leg exercise that builds strength, balance, and symmetry. Lunges target the quads, glutes, and hamstrings while challenging your stability.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80',
    muscleGroups: ['Legs'],
    equipment: 'Bodyweight',
    difficulty: 'Beginner',
    sets: 3,
    reps: '12-15',
    duration: 14,
    caloriesBurned: 110,
    rating: 4.2,
    instructions: [
      'Stand tall with feet hip-width apart and hands on hips.',
      'Step forward with one leg and lower until both knees form 90-degree angles.',
      'Push through your front heel to return to standing.',
      'Alternate legs with each rep for balanced development.',
    ],
  },
  {
    id: 10,
    name: 'Overhead Press',
    description:
      'Build powerful shoulders and triceps with the overhead press. This compound movement also strengthens the core as you stabilize the weight overhead.',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&q=80',
    muscleGroups: ['Shoulders'],
    equipment: 'Barbell',
    difficulty: 'Intermediate',
    sets: 4,
    reps: '8-10',
    duration: 18,
    caloriesBurned: 140,
    rating: 4.5,
    instructions: [
      'Clean the bar to shoulder height with palms facing forward.',
      'Brace your core and keep your glutes tight.',
      'Press the bar straight up until your arms are fully extended.',
      'Lower with control back to your shoulders and repeat.',
    ],
  },
  {
    id: 11,
    name: 'Dumbbell Row',
    description:
      'A unilateral back exercise that builds a strong, thick back while correcting imbalances. Targets the lats, rhomboids, and biceps.',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    muscleGroups: ['Back'],
    equipment: 'Dumbbells',
    difficulty: 'Intermediate',
    sets: 3,
    reps: '10-12',
    duration: 15,
    caloriesBurned: 100,
    rating: 4.4,
    instructions: [
      'Place one knee and hand on a bench, other foot on the floor.',
      'Grip the dumbbell with your free hand, arm fully extended.',
      'Pull the dumbbell toward your hip, squeezing your shoulder blade.',
      'Lower slowly back to the start and repeat on both sides.',
    ],
  },
  {
    id: 12,
    name: 'Kettlebell Swing',
    description:
      'A dynamic full-body movement that builds explosive posterior chain strength. The swing is great for conditioning, power, and metabolic training.',
    image: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80',
    muscleGroups: ['Legs', 'Core'],
    equipment: 'Kettlebell',
    difficulty: 'Intermediate',
    sets: 3,
    reps: '15-20',
    duration: 12,
    caloriesBurned: 130,
    rating: 4.3,
    instructions: [
      'Stand with feet slightly wider than shoulder-width, kettlebell between them.',
      'Hinge at the hips and grip the kettlebell with both hands.',
      'Hike the bell back between your legs like a football center.',
      'Drive through your hips and snap them forward to swing the bell up to chest level.',
    ],
  },
];

export default fallbackWorkouts;
